# Generated by Django 4.1 on 2022-08-21 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id_search', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('code', models.TextField()),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=[])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_created', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
